project:
  type: website
  output-dir: docs

website:
  title: "MY PORTFOLIO"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - text: "Home"
        href: index.html  # Ensure this is .html
      - text: "Project Experience"
        href: projectexperience.html  # Ensure this is .html
      - text: "Travel Experience"
        href: travelexperience.html  # Ensure this is .html
      - text: "Reflection"
        href: reflection.html  # Ensure this is .html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left
